name: netflix_
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.5
  firebase_analytics: ^9.1.9
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.6.0
  get: ^4.6.5
  google_sign_in: ^5.3.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  chewie: ^1.2.0
  video_player: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/video/
