// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp7gyh8Lpea_5SnlUgMyJOwcHNrKuwm0E',
    appId: '1:317721416299:web:148f375d1dd38db7c1172e',
    messagingSenderId: '317721416299',
    projectId: 'auth-281b4',
    authDomain: 'auth-281b4.firebaseapp.com',
    storageBucket: 'auth-281b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8dBi8KGY8Vzy9bnBpw0nWieuXTLT7vg',
    appId: '1:317721416299:android:aeaf4b86bdd0a201c1172e',
    messagingSenderId: '317721416299',
    projectId: 'auth-281b4',
    storageBucket: 'auth-281b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_rpO5Ofqmy79uyqwX183EtLcRiiUE3Y',
    appId: '1:317721416299:ios:a117bc4881d4dfb0c1172e',
    messagingSenderId: '317721416299',
    projectId: 'auth-281b4',
    storageBucket: 'auth-281b4.appspot.com',
    iosClientId: '317721416299-i50aaecuim37oiei677r08ef5p005q7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH_rpO5Ofqmy79uyqwX183EtLcRiiUE3Y',
    appId: '1:317721416299:ios:a117bc4881d4dfb0c1172e',
    messagingSenderId: '317721416299',
    projectId: 'auth-281b4',
    storageBucket: 'auth-281b4.appspot.com',
    iosClientId: '317721416299-i50aaecuim37oiei677r08ef5p005q7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );
}
